#!/bin/bash
# Bundle sqlift and sqldeep implementations into dist/sqlpipe.cpp and keep the
# sqlift C API block in dist/sqlpipe.h in lockstep with vendor/include/sqlift.h.
#
# This script:
# 1. Copies dist files from vendored submodules into vendor/{include,src}/
# 2. Regenerates the sqlift API block in dist/sqlpipe.h (markers below)
# 3. Truncates dist/sqlpipe.cpp at the bundle marker
# 4. Appends sqlift.cpp and sqldeep.cpp (stripped of their own includes)
# 5. Copies updated dist files to Go and Swift wrappers
# 6. Syncs deepparser sources into Go/Swift wrappers
#
# Header sections managed by this script:
#   dist/sqlpipe.h — between
#     "// ── Bundled: sqlift (schema migration) ──────────────────────────"
#     and
#     "// ── sqlpipe ────────────────────────────────────────────────────"
#   (version macros, error enum, SQLIFT_ALLOW_* flags, sqlift_apply_options,
#    function prototypes from vendor/include/sqlift.h, plus sqlift_db_wrap)
#
# Usage: scripts/bundle-deps.sh

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

SQLDEEP_SUB=vendor/github.com/marcelocantos/sqldeep
SQLIFT_SUB=vendor/github.com/marcelocantos/sqlift
DEEPPARSER_SUB=vendor/github.com/marcelocantos/deepparser
MARKER="// ── BUNDLED DEPENDENCIES (auto-generated by scripts/bundle-deps.sh) ──"

# ── 1. Copy dist files from submodules ──────────────────────────
if [ -d "$SQLDEEP_SUB/dist" ]; then
    cp "$SQLDEEP_SUB/dist/sqldeep.h" vendor/include/sqldeep.h
    cp "$SQLDEEP_SUB/dist/sqldeep.cpp" vendor/src/sqldeep.cpp
    cp "$SQLDEEP_SUB/dist/sqldeep_xml.h" vendor/include/sqldeep_xml.h
    cp "$SQLDEEP_SUB/dist/sqldeep_xml.c" vendor/src/sqldeep_xml.c
    echo "Copied sqldeep dist from submodule ($(cd "$SQLDEEP_SUB" && git describe --tags --always))"
else
    echo "Error: $SQLDEEP_SUB not found — run 'git submodule update --init'" >&2
    exit 1
fi

if [ -d "$SQLIFT_SUB/dist" ]; then
    cp "$SQLIFT_SUB/dist/sqlift.h" vendor/include/sqlift.h
    cp "$SQLIFT_SUB/dist/sqlift.cpp" vendor/src/sqlift.cpp
    echo "Copied sqlift dist from submodule ($(cd "$SQLIFT_SUB" && git describe --tags --always))"
else
    echo "Error: $SQLIFT_SUB not found — run 'git submodule update --init'" >&2
    exit 1
fi

# ── 1b. Sync sqlift C API block into dist/sqlpipe.h ─────────────
# Mirrors version macros, error enum, allow flags, apply_options, and
# function prototypes from vendor/include/sqlift.h so a submodule bump
# cannot leave dist/sqlpipe.h missing new SQLIFT_ALLOW_* identifiers.
SQLIFT_H_BEGIN='// ── Bundled: sqlift (schema migration) ──────────────────────────'
SQLIFT_H_END='// ── sqlpipe ────────────────────────────────────────────────────'
python3 - "$SQLIFT_H_BEGIN" "$SQLIFT_H_END" <<'PY'
import re, sys
from pathlib import Path

begin, end = sys.argv[1], sys.argv[2]
src = Path("vendor/include/sqlift.h").read_text()
header = Path("dist/sqlpipe.h").read_text()

# Version macros
ver = re.search(
    r"(#define SQLIFT_VERSION\s+\".*?\"\n"
    r"#define SQLIFT_VERSION_MAJOR\s+\d+\n"
    r"#define SQLIFT_VERSION_MINOR\s+\d+\n"
    r"#define SQLIFT_VERSION_PATCH\s+\d+\n)",
    src,
)
if not ver:
    sys.exit("Error: SQLIFT_VERSION macros not found in vendor/include/sqlift.h")

# Error enum
enum = re.search(r"enum sqlift_error_type \{.*?\};", src, re.S)
if not enum:
    sys.exit("Error: sqlift_error_type enum not found")

# All SQLIFT_ALLOW_* macros (single- and multi-line)
allows = re.findall(
    r"#define SQLIFT_ALLOW_\w+\s+(?:\(\d+u\s*<<\s*\d+\)|\d+u|"
    r"\([^)]*(?:\\?\n[^)]*)*\))",
    src,
)
if not allows:
    sys.exit("Error: SQLIFT_ALLOW_* macros not found")

opts = re.search(
    r"typedef struct sqlift_apply_options \{.*?\}\s*sqlift_apply_options;",
    src,
    re.S,
)
if not opts:
    sys.exit("Error: sqlift_apply_options not found")

# Function prototypes: keep them compact (strip // comments between decls).
body = src.split("typedef struct sqlift_db sqlift_db;")[1]
body = body.split("#ifdef __cplusplus")[0]
# Drop pure comment lines and collapse blank runs.
lines = []
for line in body.splitlines():
    s = line.strip()
    if not s or s.startswith("//"):
        continue
    lines.append(line.rstrip())
funcs = "\n".join(lines).strip()

allow_block = "\n".join(allows)
# Normalise multi-line ALLOW_ALL to a stable wrap
allow_block = re.sub(
    r"#define SQLIFT_ALLOW_ALL\s+\(([^)]+)\)",
    lambda m: "#define SQLIFT_ALLOW_ALL            ("
    + " ".join(m.group(1).split())
    + ")",
    allow_block,
    flags=re.S,
)

block = f"""{begin}
// Declarative SQLite schema diffing and migration.
// Auto-synced from vendor/include/sqlift.h by scripts/bundle-deps.sh —
// do not edit this block by hand.

{ver.group(1).rstrip()}

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

{enum.group(0)}

// Atomic permission bits for sqlift_apply_options.allow.
{allow_block}

{opts.group(0)}

typedef struct sqlift_db sqlift_db;

{funcs}
// sqlpipe shim: wrap an existing sqlite3* (not owned). Implemented in the
// bundled sqlift section of dist/sqlpipe.cpp by scripts/bundle-deps.sh.
sqlift_db* sqlift_db_wrap(sqlite3* handle);

#ifdef __cplusplus
}}
#endif

"""

if begin not in header or end not in header:
    sys.exit("Error: sqlift block markers not found in dist/sqlpipe.h")
pre, rest = header.split(begin, 1)
_, post = rest.split(end, 1)
Path("dist/sqlpipe.h").write_text(pre + block + end + post)
print("Synced sqlift API block into dist/sqlpipe.h")
PY

# ── 2. Truncate at marker ──────────────────────────────────────
MARKER_LINE=$(grep -n "^${MARKER}\$" dist/sqlpipe.cpp | head -1 | cut -d: -f1)
if [ -z "$MARKER_LINE" ]; then
    echo "Error: bundle marker not found in dist/sqlpipe.cpp" >&2
    exit 1
fi
# Keep everything up to and including the marker + its comment line
head -n "$((MARKER_LINE + 1))" dist/sqlpipe.cpp > dist/sqlpipe.cpp.tmp

# ── 3. Append sqlift ───────────────────────────────────────────
{
    echo ""
    echo "// ── sqlift (schema migration) ────────────────────────────────────"
    echo "// Source: vendor/src/sqlift.cpp"
    echo ""
    # Strip own header include (C API types already in sqlpipe.h).
    # Rename internal helpers that collide across bundled deps.
    gsed -E '
        /^#include [<"]sqlift\.h[">]/d
        /^#pragma once/d
        s/\bdup_str\b/sqlift_dup_str/g
        s/\bclear_error\b/sqlift_clear_error/g
        s/\bset_error\b/sqlift_set_error/g
    ' vendor/src/sqlift.cpp
} >> dist/sqlpipe.cpp.tmp

# Patch sqlift_db and sqlift_db_close to support borrowed handles,
# and append sqlift_db_wrap.
# TODO: upstream to sqlift — the C API should accept sqlite3* directly.
gsed -i -E '
    # Add owns flag to sqlift_db struct
    s/^(struct sqlift_db \{)/\1\n    bool owns = true;/

    # Patch sqlift_db_close to skip close for borrowed handles
    /^void sqlift_db_close\(sqlift_db\* db\) \{/{
        N
        s/delete db;/if (!db->owns) { \/* borrowed — null out handle so ~Database skips close *\/\n        sqlite3 *null = nullptr;\n        memcpy(static_cast<void*>(\&db->db), \&null, sizeof(sqlite3*));\n    }\n    delete db;/
    }
' dist/sqlpipe.cpp.tmp

cat <<'SHIM' >> dist/sqlpipe.cpp.tmp

// ── sqlift_db_wrap (sqlpipe shim) ───────────────────────────────────
// Wraps an existing sqlite3* for use with sqlift C API functions.
// The handle is NOT owned — sqlift_db_close will not close it.
// TODO: upstream to sqlift — the C API should accept sqlite3* directly.

extern "C" sqlift_db* sqlift_db_wrap(sqlite3* handle) {
    auto* sdb = new sqlift_db(":memory:", 0);
    // Close the dummy :memory: db and swap in the borrowed handle.
    sqlite3_close(sdb->db.get());
    sqlite3** pdb = reinterpret_cast<sqlite3**>(&sdb->db);
    *pdb = handle;
    sdb->owns = false;
    return sdb;
}
SHIM

# ── 4. Append sqldeep ──────────────────────────────────────────
{
    echo ""
    echo "// ── sqldeep (query transpiler) ──────────────────────────────────"
    echo "// Source: vendor/src/sqldeep.cpp"
    echo ""
    gsed -E '
        /^#include [<"]sqldeep\.h[">]/d
        /^#pragma once/d
        s/\bdup_str\b/sqldeep_dup_str/g
        s/\bclear_error\b/sqldeep_clear_error/g
        s/\bset_error\b/sqldeep_set_error/g
    ' vendor/src/sqldeep.cpp
} >> dist/sqlpipe.cpp.tmp

# ── 5. Append sqldeep_xml (C runtime functions) ──────────────
{
    echo ""
    echo "// ── sqldeep_xml (XML runtime for SQLite) ───────────────────────"
    echo "// Source: vendor/src/sqldeep_xml.c"
    echo ""
    echo 'extern "C" {'
    gsed -E '
        /^#include [<"]sqldeep_xml\.h[">]/d
        /^#include [<"]sqlite3\.h[">]/d
        /^#pragma once/d
    ' vendor/src/sqldeep_xml.c
    echo '} // extern "C"'
} >> dist/sqlpipe.cpp.tmp

mv dist/sqlpipe.cpp.tmp dist/sqlpipe.cpp
echo "Bundled sqlift + sqldeep + sqldeep_xml into dist/sqlpipe.cpp"

# ── 5. Copy to wrappers ───────────────────────────────────────
cp dist/sqlpipe.{h,cpp} go/sqlpipe/internal/c/
cp dist/sqlpipe.{h,cpp} swift/Sources/CSqlpipe/
cp dist/sqlpipe.h swift/Sources/CSqlpipe/include/

# The Go module vendors a copy of the C-API shim under internal/c/ as well as
# the top-level go/sqlpipe/ copy: the cgo-generated prolog resolves
# #include "sqlpipe_capi.h" via -I internal/c, so a stale copy there silently
# feeds cgo the wrong prototypes. Keep it in lockstep with the source of truth.
cp go/sqlpipe/sqlpipe_capi.{h,cpp} go/sqlpipe/internal/c/

# ── 6. Sync deepparser sources to wrappers ────────────────────
# The bundled sqldeep parses input via deepparser. Wrappers must
# vendor deepparser sources so consumers don't need to fetch them.
if [ -d "$DEEPPARSER_SUB/src" ]; then
    dp_files=(arena.c arena.h liteparser.c liteparser.h liteparser_internal.h lp_lempar.c lp_tokenize.c lp_unparse.c parse.c parse.h)
    # Both the Go and Swift wrappers compile the bundled sqlpipe.cpp, which
    # parses via deepparser; each must vendor the deepparser sources so
    # consumers don't need to fetch them. (The Swift package excludes
    # lp_lempar.c from compilation via Package.swift — it is a lemon template.)
    for dest in go/sqlpipe/internal/c/deepparser swift/Sources/CSqlpipe/deepparser; do
        mkdir -p "$dest"
        for f in "${dp_files[@]}"; do
            cp "$DEEPPARSER_SUB/src/$f" "$dest/"
        done
    done
    echo "Copied deepparser sources to Go and Swift wrappers ($(cd "$DEEPPARSER_SUB" && git describe --tags --always))"
else
    echo "Warning: $DEEPPARSER_SUB not found — wrapper deepparser sources not refreshed" >&2
fi
echo "Copied to Go and Swift wrappers"
