#!/bin/bash
# Bundle sqlift and sqldeep implementations into dist/sqlpipe.cpp.
#
# This script:
# 1. Copies dist files from vendored submodules into vendor/{include,src}/
# 2. Truncates dist/sqlpipe.cpp at the bundle marker
# 3. Appends sqlift.cpp and sqldeep.cpp (stripped of their own includes)
# 4. Copies updated dist files to Go and Swift wrappers
#
# Usage: scripts/bundle-deps.sh

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

SQLDEEP_SUB=vendor/github.com/marcelocantos/sqldeep
SQLIFT_SUB=vendor/github.com/marcelocantos/sqlift
MARKER="// ── BUNDLED DEPENDENCIES (auto-generated by scripts/bundle-deps.sh) ──"

# ── 1. Copy dist files from submodules ──────────────────────────
if [ -d "$SQLDEEP_SUB/dist" ]; then
    cp "$SQLDEEP_SUB/dist/sqldeep.h" vendor/include/sqldeep.h
    cp "$SQLDEEP_SUB/dist/sqldeep.cpp" vendor/src/sqldeep.cpp
    cp "$SQLDEEP_SUB/dist/sqldeep_xml.h" vendor/include/sqldeep_xml.h
    cp "$SQLDEEP_SUB/dist/sqldeep_xml.c" vendor/src/sqldeep_xml.c
    echo "Copied sqldeep dist from submodule ($(cd "$SQLDEEP_SUB" && git describe --tags --always))"
else
    echo "Error: $SQLDEEP_SUB not found — run 'git submodule update --init'" >&2
    exit 1
fi

if [ -d "$SQLIFT_SUB/dist" ]; then
    cp "$SQLIFT_SUB/dist/sqlift.h" vendor/include/sqlift.h
    cp "$SQLIFT_SUB/dist/sqlift.cpp" vendor/src/sqlift.cpp
    echo "Copied sqlift dist from submodule ($(cd "$SQLIFT_SUB" && git describe --tags --always))"
else
    echo "Error: $SQLIFT_SUB not found — run 'git submodule update --init'" >&2
    exit 1
fi

# ── 2. Truncate at marker ──────────────────────────────────────
MARKER_LINE=$(grep -n "^${MARKER}\$" dist/sqlpipe.cpp | head -1 | cut -d: -f1)
if [ -z "$MARKER_LINE" ]; then
    echo "Error: bundle marker not found in dist/sqlpipe.cpp" >&2
    exit 1
fi
# Keep everything up to and including the marker + its comment line
head -n "$((MARKER_LINE + 1))" dist/sqlpipe.cpp > dist/sqlpipe.cpp.tmp

# ── 3. Append sqlift ───────────────────────────────────────────
{
    echo ""
    echo "// ── sqlift (schema migration) ────────────────────────────────────"
    echo "// Source: vendor/src/sqlift.cpp"
    echo ""
    # Strip own header include (C API types already in sqlpipe.h).
    # Rename internal helpers that collide across bundled deps.
    gsed -E '
        /^#include [<"]sqlift\.h[">]/d
        /^#pragma once/d
        s/\bdup_str\b/sqlift_dup_str/g
        s/\bclear_error\b/sqlift_clear_error/g
        s/\bset_error\b/sqlift_set_error/g
    ' vendor/src/sqlift.cpp
} >> dist/sqlpipe.cpp.tmp

# Patch sqlift_db and sqlift_db_close to support borrowed handles,
# and append sqlift_db_wrap.
# TODO: upstream to sqlift — the C API should accept sqlite3* directly.
gsed -i -E '
    # Add owns flag to sqlift_db struct
    s/^(struct sqlift_db \{)/\1\n    bool owns = true;/

    # Patch sqlift_db_close to skip close for borrowed handles
    /^void sqlift_db_close\(sqlift_db\* db\) \{/{
        N
        s/delete db;/if (!db->owns) { \/* borrowed — null out handle so ~Database skips close *\/\n        sqlite3 *null = nullptr;\n        memcpy(static_cast<void*>(\&db->db), \&null, sizeof(sqlite3*));\n    }\n    delete db;/
    }
' dist/sqlpipe.cpp.tmp

cat <<'SHIM' >> dist/sqlpipe.cpp.tmp

// ── sqlift_db_wrap (sqlpipe shim) ───────────────────────────────────
// Wraps an existing sqlite3* for use with sqlift C API functions.
// The handle is NOT owned — sqlift_db_close will not close it.
// TODO: upstream to sqlift — the C API should accept sqlite3* directly.

extern "C" sqlift_db* sqlift_db_wrap(sqlite3* handle) {
    auto* sdb = new sqlift_db(":memory:", 0);
    // Close the dummy :memory: db and swap in the borrowed handle.
    sqlite3_close(sdb->db.get());
    sqlite3** pdb = reinterpret_cast<sqlite3**>(&sdb->db);
    *pdb = handle;
    sdb->owns = false;
    return sdb;
}
SHIM

# ── 4. Append sqldeep ──────────────────────────────────────────
{
    echo ""
    echo "// ── sqldeep (query transpiler) ──────────────────────────────────"
    echo "// Source: vendor/src/sqldeep.cpp"
    echo ""
    gsed -E '
        /^#include [<"]sqldeep\.h[">]/d
        /^#pragma once/d
        s/\bdup_str\b/sqldeep_dup_str/g
        s/\bclear_error\b/sqldeep_clear_error/g
        s/\bset_error\b/sqldeep_set_error/g
    ' vendor/src/sqldeep.cpp
} >> dist/sqlpipe.cpp.tmp

# ── 5. Append sqldeep_xml (C runtime functions) ──────────────
{
    echo ""
    echo "// ── sqldeep_xml (XML runtime for SQLite) ───────────────────────"
    echo "// Source: vendor/src/sqldeep_xml.c"
    echo ""
    echo 'extern "C" {'
    gsed -E '
        /^#include [<"]sqldeep_xml\.h[">]/d
        /^#include [<"]sqlite3\.h[">]/d
        /^#pragma once/d
    ' vendor/src/sqldeep_xml.c
    echo '} // extern "C"'
} >> dist/sqlpipe.cpp.tmp

mv dist/sqlpipe.cpp.tmp dist/sqlpipe.cpp
echo "Bundled sqlift + sqldeep + sqldeep_xml into dist/sqlpipe.cpp"

# ── 5. Copy to wrappers ───────────────────────────────────────
cp dist/sqlpipe.{h,cpp} go/sqlpipe/internal/c/
cp dist/sqlpipe.{h,cpp} swift/Sources/CSqlpipe/
cp dist/sqlpipe.h swift/Sources/CSqlpipe/include/
echo "Copied to Go and Swift wrappers"
