#!/bin/bash
# Bundle sqlift and sqldeep implementations into dist/sqlpipe.cpp.
#
# This script:
# 1. Copies sqldeep dist files from the sibling repo into vendor/
# 2. Truncates dist/sqlpipe.cpp at the bundle marker
# 3. Appends sqlift.cpp and sqldeep.cpp (stripped of their own includes)
# 4. Copies updated dist files to Go and Swift wrappers
#
# Usage: scripts/bundle-deps.sh [--sqldeep-dir DIR]
# Default sqldeep dir: ../sqldeep

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

SQLDEEP_DIR="${1:-../sqldeep}"
MARKER="// ── BUNDLED DEPENDENCIES (auto-generated by scripts/bundle-deps.sh) ──"

# ── 1. Vendor sqldeep ───────────────────────────────────────────
if [ -d "$SQLDEEP_DIR/dist" ]; then
    cp "$SQLDEEP_DIR/dist/sqldeep.h" vendor/include/sqldeep.h
    cp "$SQLDEEP_DIR/dist/sqldeep.cpp" vendor/src/sqldeep.cpp
    cp "$SQLDEEP_DIR/dist/sqldeep_xml.h" vendor/include/sqldeep_xml.h
    cp "$SQLDEEP_DIR/dist/sqldeep_xml.c" vendor/src/sqldeep_xml.c
    echo "Vendored sqldeep from $SQLDEEP_DIR"
else
    echo "Warning: $SQLDEEP_DIR not found, using existing vendor/src/sqldeep.cpp"
fi

# ── 2. Truncate at marker ──────────────────────────────────────
MARKER_LINE=$(grep -n "^${MARKER}\$" dist/sqlpipe.cpp | head -1 | cut -d: -f1)
if [ -z "$MARKER_LINE" ]; then
    echo "Error: bundle marker not found in dist/sqlpipe.cpp" >&2
    exit 1
fi
# Keep everything up to and including the marker + its comment line
head -n "$((MARKER_LINE + 1))" dist/sqlpipe.cpp > dist/sqlpipe.cpp.tmp

# ── 3. Append sqlift ───────────────────────────────────────────
{
    echo ""
    echo "// ── sqlift (schema migration) ────────────────────────────────────"
    echo "// Source: vendor/src/sqlift.cpp"
    echo ""
    # Strip own header includes and system includes already pulled in.
    # Rename internal helpers that collide across bundled deps.
    gsed -E '
        /^#include [<"]sqlift\.h[">]/d
        /^#pragma once/d
        s/\bdup_str\b/sqlift_dup_str/g
        s/\bclear_error\b/sqlift_clear_error/g
        s/\bset_error\b/sqlift_set_error/g
    ' vendor/src/sqlift.cpp
} >> dist/sqlpipe.cpp.tmp

# ── 4. Append sqldeep ──────────────────────────────────────────
{
    echo ""
    echo "// ── sqldeep (query transpiler) ──────────────────────────────────"
    echo "// Source: vendor/src/sqldeep.cpp"
    echo ""
    gsed -E '
        /^#include [<"]sqldeep\.h[">]/d
        /^#pragma once/d
        s/\bdup_str\b/sqldeep_dup_str/g
        s/\bclear_error\b/sqldeep_clear_error/g
        s/\bset_error\b/sqldeep_set_error/g
    ' vendor/src/sqldeep.cpp
} >> dist/sqlpipe.cpp.tmp

# ── 5. Append sqldeep_xml (C runtime functions) ──────────────
{
    echo ""
    echo "// ── sqldeep_xml (XML runtime for SQLite) ───────────────────────"
    echo "// Source: vendor/src/sqldeep_xml.c"
    echo ""
    echo 'extern "C" {'
    gsed -E '
        /^#include [<"]sqldeep_xml\.h[">]/d
        /^#include [<"]sqlite3\.h[">]/d
        /^#pragma once/d
    ' vendor/src/sqldeep_xml.c
    echo '} // extern "C"'
} >> dist/sqlpipe.cpp.tmp

mv dist/sqlpipe.cpp.tmp dist/sqlpipe.cpp
echo "Bundled sqlift + sqldeep + sqldeep_xml into dist/sqlpipe.cpp"

# ── 5. Copy to wrappers ───────────────────────────────────────
cp dist/sqlpipe.{h,cpp} go/sqlpipe/internal/c/
cp dist/sqlpipe.{h,cpp} swift/Sources/CSqlpipe/
cp dist/sqlpipe.h swift/Sources/CSqlpipe/include/
echo "Copied to Go and Swift wrappers"
